In [7]:
import sys
import os

current_dir = os.getcwd()

parent_dir = os.path.dirname(current_dir)
if parent_dir not in sys.path:
    sys.path.append(parent_dir)

## **Data Check**

In [ ]:
import os

RAW_DATA_PATH = '../data/raw/'

def list_files_tree(startpath):
    print(f"--- DIRECTORY STRUCTURE: {startpath} ---")
    for root, dirs, files in os.walk(startpath):
        level = root.replace(startpath, '').count(os.sep)
        indent = ' ' * 4 * (level)
        print('{}{}/'.format(indent, os.path.basename(root)))
        subindent = ' ' * 4 * (level + 1)
        for f in files:
            print('{}{}'.format(subindent, f))

list_files_tree(RAW_DATA_PATH)

--- DIRECTORY STRUCTURE: ../data/raw/ ---
/
    application_test.csv
    application_train.csv
    bureau.csv
    bureau_balance.csv
    credit_card_balance.csv
    HomeCredit_columns_description.csv
    installments_payments.csv
    POS_CASH_balance.csv
    previous_application.csv
    sample_submission.csv

In [1]:
import os
import pandas as pd

# Configuration
RAW_DATA_PATH = '../data/raw/'
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

def inspect_data_inventory(path):
    # List all CSV files
    try:
        files = [f for f in os.listdir(path) if f.endswith('.csv')]
    except FileNotFoundError:
        print(f"[ERROR] Directory not found: {path}")
        return

    print(f"--- DATA INVENTORY REPORT ({len(files)} files detected) ---")
    print(f"Path: {path}\n")

    for file in files:
        file_path = os.path.join(path, file)
        try:
            # Read only the first 3 rows for quick inspection
            df_preview = pd.read_csv(file_path, nrows=3)
            
            print(f"[FILE] {file}")
            print(f"   Shape (Rows, Cols): {df_preview.shape}")
                        
            # Column Check for Identification
            cols = df_preview.columns.tolist()
            
            # Check for GMSC Target
            if 'SeriousDlqin2yrs' in cols:
                print("   [TYPE] Give Me Some Credit (GMSC) Dataset")
                print("   [ROLE] Potential Base Table (Target Found)")
            
            # Check for Home Credit Target
            elif 'TARGET' in cols:
                print("   [TYPE] Home Credit Default Risk (HCDR) Dataset")
                print("   [ROLE] Potential Base Table (Target Found)")
            
            # Check for IDs
            elif 'SK_ID_CURR' in cols:
                print("   [TYPE] Home Credit Auxiliary Table")
                print("   [ROLE] Feature Table (Join required via SK_ID_CURR)")
            
            else:
                print("   [TYPE] Unknown / Other")
            
            print(f"   Columns: {cols[:500]} ...") 
            print("-" * 60)
            
        except Exception as e:
            print(f"[ERROR] Could not read {file}: {e}")
            print("-" * 60)

# Execute the inspection
inspect_data_inventory(RAW_DATA_PATH)

--- DATA INVENTORY REPORT (10 files detected) ---
Path: ../data/raw/

[FILE] application_test.csv
   Shape (Rows, Cols): (3, 121)
   [TYPE] Home Credit Auxiliary Table
   [ROLE] Feature Table (Join required via SK_ID_CURR)
   Columns: ['SK_ID_CURR', 'NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'OWN_CAR_AGE', 'FLAG_MOBIL', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE', 'FLAG_CONT_MOBILE', 'FLAG_PHONE', 'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS', 'REGION_RATING_CLIENT', 'REGION_RATING_CLIENT_W_CITY', 'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START', 'REG_REGION_NOT_LIVE_REGION', 'REG_REGION_NOT_WORK_REGION', 'LIVE_REGION_NOT_WORK_REGION', 'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY', 'LIVE_CITY_NOT_WORK_CITY', 'ORGANIZATION_TYPE', 'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'APARTMENTS_AVG', 'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG', 'YEARS_BUILD_AVG', 'COMMONAREA_AVG', 'ELEVATORS_AVG', 'ENTRANCES_AVG'] ...
------------------------------------------------------------
[FILE] application_train.csv
   Shape (Rows, Cols): (3, 122)
   [TYPE] Home Credit Default Risk (HCDR) Dataset
   [ROLE] Potential Base Table (Target Found)
   Columns: ['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'OWN_CAR_AGE', 'FLAG_MOBIL', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE', 'FLAG_CONT_MOBILE', 'FLAG_PHONE', 'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS', 'REGION_RATING_CLIENT', 'REGION_RATING_CLIENT_W_CITY', 'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START', 'REG_REGION_NOT_LIVE_REGION', 'REG_REGION_NOT_WORK_REGION', 'LIVE_REGION_NOT_WORK_REGION', 'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY', 'LIVE_CITY_NOT_WORK_CITY', 'ORGANIZATION_TYPE', 'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'APARTMENTS_AVG', 'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG', 'YEARS_BUILD_AVG', 'COMMONAREA_AVG', 'ELEVATORS_AVG'] ...
------------------------------------------------------------
[FILE] bureau.csv
   Shape (Rows, Cols): (3, 17)
   [TYPE] Home Credit Auxiliary Table
   [ROLE] Feature Table (Join required via SK_ID_CURR)
   Columns: ['SK_ID_CURR', 'SK_ID_BUREAU', 'CREDIT_ACTIVE', 'CREDIT_CURRENCY', 'DAYS_CREDIT', 'CREDIT_DAY_OVERDUE', 'DAYS_CREDIT_ENDDATE', 'DAYS_ENDDATE_FACT', 'AMT_CREDIT_MAX_OVERDUE', 'CNT_CREDIT_PROLONG', 'AMT_CREDIT_SUM', 'AMT_CREDIT_SUM_DEBT', 'AMT_CREDIT_SUM_LIMIT', 'AMT_CREDIT_SUM_OVERDUE', 'CREDIT_TYPE', 'DAYS_CREDIT_UPDATE', 'AMT_ANNUITY'] ...
------------------------------------------------------------
[FILE] bureau_balance.csv
   Shape (Rows, Cols): (3, 3)
   [TYPE] Unknown / Other (Likely Metadata/Description)
   Columns: ['SK_ID_BUREAU', 'MONTHS_BALANCE', 'STATUS'] ...
------------------------------------------------------------
[FILE] credit_card_balance.csv
   Shape (Rows, Cols): (3, 23)
   [TYPE] Home Credit Auxiliary Table
   [ROLE] Feature Table (Join required via SK_ID_CURR)
   Columns: ['SK_ID_PREV', 'SK_ID_CURR', 'MONTHS_BALANCE', 'AMT_BALANCE', 'AMT_CREDIT_LIMIT_ACTUAL', 'AMT_DRAWINGS_ATM_CURRENT', 'AMT_DRAWINGS_CURRENT', 'AMT_DRAWINGS_OTHER_CURRENT', 'AMT_DRAWINGS_POS_CURRENT', 'AMT_INST_MIN_REGULARITY', 'AMT_PAYMENT_CURRENT', 'AMT_PAYMENT_TOTAL_CURRENT', 'AMT_RECEIVABLE_PRINCIPAL', 'AMT_RECIVABLE', 'AMT_TOTAL_RECEIVABLE', 'CNT_DRAWINGS_ATM_CURRENT', 'CNT_DRAWINGS_CURRENT', 'CNT_DRAWINGS_OTHER_CURRENT', 'CNT_DRAWINGS_POS_CURRENT', 'CNT_INSTALMENT_MATURE_CUM', 'NAME_CONTRACT_STATUS', 'SK_DPD', 'SK_DPD_DEF'] ...
------------------------------------------------------------
   [WARNING] 'HomeCredit_columns_description.csv' UTF-8 ile okunamadı, 'ISO-8859-1' ile decode edildi.
[FILE] HomeCredit_columns_description.csv
   Shape (Rows, Cols): (3, 5)
   [TYPE] Unknown / Other (Likely Metadata/Description)
   Columns: ['Unnamed: 0', 'Table', 'Row', 'Description', 'Special'] ...
------------------------------------------------------------
[FILE] installments_payments.csv
   Shape (Rows, Cols): (3, 8)
   [TYPE] Home Credit Auxiliary Table
   [ROLE] Feature Table (Join required via SK_ID_CURR)
   Columns: ['SK_ID_PREV', 'SK_ID_CURR', 'NUM_INSTALMENT_VERSION', 'NUM_INSTALMENT_NUMBER', 'DAYS_INSTALMENT', 'DAYS_ENTRY_PAYMENT', 'AMT_INSTALMENT', 'AMT_PAYMENT'] ...
------------------------------------------------------------
[FILE] POS_CASH_balance.csv
   Shape (Rows, Cols): (3, 8)
   [TYPE] Home Credit Auxiliary Table
   [ROLE] Feature Table (Join required via SK_ID_CURR)
   Columns: ['SK_ID_PREV', 'SK_ID_CURR', 'MONTHS_BALANCE', 'CNT_INSTALMENT', 'CNT_INSTALMENT_FUTURE', 'NAME_CONTRACT_STATUS', 'SK_DPD', 'SK_DPD_DEF'] ...
------------------------------------------------------------
[FILE] previous_application.csv
   Shape (Rows, Cols): (3, 37)
   [TYPE] Home Credit Auxiliary Table
   [ROLE] Feature Table (Join required via SK_ID_CURR)
   Columns: ['SK_ID_PREV', 'SK_ID_CURR', 'NAME_CONTRACT_TYPE', 'AMT_ANNUITY', 'AMT_APPLICATION', 'AMT_CREDIT', 'AMT_DOWN_PAYMENT', 'AMT_GOODS_PRICE', 'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START', 'FLAG_LAST_APPL_PER_CONTRACT', 'NFLAG_LAST_APPL_IN_DAY', 'RATE_DOWN_PAYMENT', 'RATE_INTEREST_PRIMARY', 'RATE_INTEREST_PRIVILEGED', 'NAME_CASH_LOAN_PURPOSE', 'NAME_CONTRACT_STATUS', 'DAYS_DECISION', 'NAME_PAYMENT_TYPE', 'CODE_REJECT_REASON', 'NAME_TYPE_SUITE', 'NAME_CLIENT_TYPE', 'NAME_GOODS_CATEGORY', 'NAME_PORTFOLIO', 'NAME_PRODUCT_TYPE', 'CHANNEL_TYPE', 'SELLERPLACE_AREA', 'NAME_SELLER_INDUSTRY', 'CNT_PAYMENT', 'NAME_YIELD_GROUP', 'PRODUCT_COMBINATION', 'DAYS_FIRST_DRAWING', 'DAYS_FIRST_DUE', 'DAYS_LAST_DUE_1ST_VERSION', 'DAYS_LAST_DUE', 'DAYS_TERMINATION', 'NFLAG_INSURED_ON_APPROVAL'] ...
------------------------------------------------------------
[FILE] sample_submission.csv
   Shape (Rows, Cols): (3, 2)
   [TYPE] Home Credit Default Risk (HCDR) Dataset
   [ROLE] Potential Base Table (Target Found)
   Columns: ['SK_ID_CURR', 'TARGET'] ...
------------------------------------------------------------

In [2]:
import os
import pandas as pd
from IPython.display import display

RAW_DATA_PATH = '../data/raw/'
pd.set_option('display.max_columns', None) 
pd.set_option('display.width', 1000)

def preview_all_datasets(path):
    # Check if directory exists
    if not os.path.exists(path):
        print(f"[ERROR] Directory not found: {path}")
        return

    # List CSV files
    files = [f for f in os.listdir(path) if f.endswith('.csv')]
    
    if not files:
        print("[WARNING] No CSV files found in the directory.")
        return

    print(f"--- DATA CONTENT INSPECTION ({len(files)} files) ---\n")

    for file in files:
        file_path = os.path.join(path, file)
        try:
            df_preview = pd.read_csv(file_path, nrows=5)
            
            print(f"[FILE] {file}")
            print(f"[SHAPE PREVIEW] {df_preview.shape}")
            
            if 'SeriousDlqin2yrs' in df_preview.columns:
                print("[INFO] Target Variable Detected: 'SeriousDlqin2yrs' (GMSC)")
            elif 'TARGET' in df_preview.columns:
                print("[INFO] Target Variable Detected: 'TARGET' (Home Credit)")
            
            # Render the DataFrame
            display(df_preview.head())
            
            print("-" * 100)
            print("\n")
            
        except Exception as e:
            print(f"[ERROR] Failed to read {file}: {e}")

preview_all_datasets(RAW_DATA_PATH)

--- DATA CONTENT INSPECTION (10 files) ---

[FILE] application_test.csv
[SHAPE PREVIEW] (5, 121)
[INFO] Key Variable Detected: 'SK_ID_CURR' (Auxiliary Table)

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.018850,-19241,-2329,-5170.0,-812,NaN,1,1,0,1,0,1,NaN,2.0,2,2,TUESDAY,18,0,0,0,0,0,0,Kindergarten,0.752614,0.789654,0.159520,0.0660,0.0590,0.9732,NaN,NaN,NaN,0.1379,0.125,NaN,NaN,NaN,0.0505,NaN,NaN,0.0672,0.0612,0.9732,NaN,NaN,NaN,0.1379,0.125,NaN,NaN,NaN,0.0526,NaN,NaN,0.0666,0.0590,0.9732,NaN,NaN,NaN,0.1379,0.125,NaN,NaN,NaN,0.0514,NaN,NaN,NaN,block of flats,0.0392,"Stone, brick",No,0.0,0.0,0.0,0.0,-1740.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.035792,-18064,-4469,-9118.0,-1623,NaN,1,1,0,1,0,0,Low-skill Laborers,2.0,2,2,FRIDAY,9,0,0,0,0,0,0,Self-employed,0.564990,0.291656,0.432962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,NaN,Working,Higher education,Married,House / apartment,0.019101,-20038,-4458,-2175.0,-3503,5.0,1,1,0,1,0,0,Drivers,2.0,2,2,MONDAY,14,0,0,0,0,0,0,Transport: type 3,NaN,0.699787,0.610991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-856.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.026392,-13976,-1866,-2000.0,-4208,NaN,1,1,0,1,1,0,Sales staff,4.0,2,2,WEDNESDAY,11,0,0,0,0,0,0,Business Entity Type 3,0.525734,0.509677,0.612704,0.3052,0.1974,0.9970,0.9592,0.1165,0.32,0.2759,0.375,0.0417,0.2042,0.2404,0.3673,0.0386,0.08,0.3109,0.2049,0.9970,0.9608,0.1176,0.3222,0.2759,0.375,0.0417,0.2089,0.2626,0.3827,0.0389,0.0847,0.3081,0.1974,0.9970,0.9597,0.1173,0.32,0.2759,0.375,0.0417,0.2078,0.2446,0.3739,0.0388,0.0817,reg oper account,block of flats,0.3700,Panel,No,0.0,0.0,0.0,0.0,-1805.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.010032,-13040,-2191,-4000.0,-4262,16.0,1,1,1,1,0,0,NaN,3.0,2,2,FRIDAY,5,0,0,0,0,1,1,Business Entity Type 3,0.202145,0.425687,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-821.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

----------------------------------------------------------------------------------------------------


[FILE] application_train.csv
[SHAPE PREVIEW] (5, 122)
[INFO] Target Variable Detected: 'TARGET' (Home Credit)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.022,0.0198,0.0,0.0,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.00,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0,-2531,26.0,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.555912,0.729567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.008019,-19005,-3039,-9833.0,-2437,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.650442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,2.0,0.0,-617.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.028663,-19932,-3038,-4311.0,-3458,NaN,1,1,0,1,0,0,Core staff,1.0,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,NaN,0.322738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1106.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

----------------------------------------------------------------------------------------------------


[FILE] bureau.csv
[SHAPE PREVIEW] (5, 17)
[INFO] Key Variable Detected: 'SK_ID_CURR' (Auxiliary Table)

   SK_ID_CURR  SK_ID_BUREAU CREDIT_ACTIVE CREDIT_CURRENCY  DAYS_CREDIT  CREDIT_DAY_OVERDUE  DAYS_CREDIT_ENDDATE  DAYS_ENDDATE_FACT  AMT_CREDIT_MAX_OVERDUE  CNT_CREDIT_PROLONG  AMT_CREDIT_SUM  AMT_CREDIT_SUM_DEBT  AMT_CREDIT_SUM_LIMIT  AMT_CREDIT_SUM_OVERDUE      CREDIT_TYPE  DAYS_CREDIT_UPDATE  AMT_ANNUITY
0      215354       5714462        Closed      currency 1         -497                   0               -153.0             -153.0                     NaN                   0         91323.0                  0.0                   NaN                     0.0  Consumer credit                -131          NaN
1      215354       5714463        Active      currency 1         -208                   0               1075.0                NaN                     NaN                   0        225000.0             171342.0                   NaN                     0.0      Credit card                 -20          NaN
2      215354       5714464        Active      currency 1         -203                   0                528.0                NaN                     NaN                   0        464323.5                  NaN                   NaN                     0.0  Consumer credit                 -16          NaN
3      215354       5714465        Active      currency 1         -203                   0                  NaN                NaN                     NaN                   0         90000.0                  NaN                   NaN                     0.0      Credit card                 -16          NaN
4      215354       5714466        Active      currency 1         -629                   0               1197.0                NaN                 77674.5                   0       2700000.0                  NaN                   NaN                     0.0  Consumer credit                 -21          NaN

----------------------------------------------------------------------------------------------------


[FILE] bureau_balance.csv
[SHAPE PREVIEW] (5, 3)

   SK_ID_BUREAU  MONTHS_BALANCE STATUS
0       5715448               0      C
1       5715448              -1      C
2       5715448              -2      C
3       5715448              -3      C
4       5715448              -4      C

----------------------------------------------------------------------------------------------------


[FILE] credit_card_balance.csv
[SHAPE PREVIEW] (5, 23)
[INFO] Key Variable Detected: 'SK_ID_CURR' (Auxiliary Table)

   SK_ID_PREV  SK_ID_CURR  MONTHS_BALANCE  AMT_BALANCE  AMT_CREDIT_LIMIT_ACTUAL  AMT_DRAWINGS_ATM_CURRENT  AMT_DRAWINGS_CURRENT  AMT_DRAWINGS_OTHER_CURRENT  AMT_DRAWINGS_POS_CURRENT  AMT_INST_MIN_REGULARITY  AMT_PAYMENT_CURRENT  AMT_PAYMENT_TOTAL_CURRENT  AMT_RECEIVABLE_PRINCIPAL  AMT_RECIVABLE  AMT_TOTAL_RECEIVABLE  CNT_DRAWINGS_ATM_CURRENT  CNT_DRAWINGS_CURRENT  CNT_DRAWINGS_OTHER_CURRENT  CNT_DRAWINGS_POS_CURRENT  CNT_INSTALMENT_MATURE_CUM NAME_CONTRACT_STATUS  SK_DPD  SK_DPD_DEF
0     2562384      378907              -6       56.970                   135000                       0.0                 877.5                         0.0                     877.5                 1700.325               1800.0                     1800.0                     0.000          0.000                 0.000                       0.0                     1                         0.0                       1.0                       35.0               Active       0           0
1     2582071      363914              -1    63975.555                    45000                    2250.0                2250.0                         0.0                       0.0                 2250.000               2250.0                     2250.0                 60175.080      64875.555             64875.555                       1.0                     1                         0.0                       0.0                       69.0               Active       0           0
2     1740877      371185              -7    31815.225                   450000                       0.0                   0.0                         0.0                       0.0                 2250.000               2250.0                     2250.0                 26926.425      31460.085             31460.085                       0.0                     0                         0.0                       0.0                       30.0               Active       0           0
3     1389973      337855              -4   236572.110                   225000                    2250.0                2250.0                         0.0                       0.0                11795.760              11925.0                    11925.0                224949.285     233048.970            233048.970                       1.0                     1                         0.0                       0.0                       10.0               Active       0           0
4     1891521      126868              -1   453919.455                   450000                       0.0               11547.0                         0.0                   11547.0                22924.890              27000.0                    27000.0                443044.395     453919.455            453919.455                       0.0                     1                         0.0                       1.0                      101.0               Active       0           0

----------------------------------------------------------------------------------------------------


   [WARNING] 'HomeCredit_columns_description.csv' UTF-8 ile okunamadı, 'ISO-8859-1' ile açıldı.
[FILE] HomeCredit_columns_description.csv
[SHAPE PREVIEW] (5, 5)

   Unnamed: 0                         Table                 Row                                        Description  Special
0           1  application_{train|test}.csv          SK_ID_CURR                           ID of loan in our sample      NaN
1           2  application_{train|test}.csv              TARGET  Target variable (1 - client with payment diffi...      NaN
2           5  application_{train|test}.csv  NAME_CONTRACT_TYPE        Identification if loan is cash or revolving      NaN
3           6  application_{train|test}.csv         CODE_GENDER                               Gender of the client      NaN
4           7  application_{train|test}.csv        FLAG_OWN_CAR                      Flag if the client owns a car      NaN

----------------------------------------------------------------------------------------------------


[FILE] installments_payments.csv
[SHAPE PREVIEW] (5, 8)
[INFO] Key Variable Detected: 'SK_ID_CURR' (Auxiliary Table)

   SK_ID_PREV  SK_ID_CURR  NUM_INSTALMENT_VERSION  NUM_INSTALMENT_NUMBER  DAYS_INSTALMENT  DAYS_ENTRY_PAYMENT  AMT_INSTALMENT  AMT_PAYMENT
0     1054186      161674                     1.0                      6          -1180.0             -1187.0        6948.360     6948.360
1     1330831      151639                     0.0                     34          -2156.0             -2156.0        1716.525     1716.525
2     2085231      193053                     2.0                      1            -63.0               -63.0       25425.000    25425.000
3     2452527      199697                     1.0                      3          -2418.0             -2426.0       24350.130    24350.130
4     2714724      167756                     1.0                      2          -1383.0             -1366.0        2165.040     2160.585

----------------------------------------------------------------------------------------------------


[FILE] POS_CASH_balance.csv
[SHAPE PREVIEW] (5, 8)
[INFO] Key Variable Detected: 'SK_ID_CURR' (Auxiliary Table)

   SK_ID_PREV  SK_ID_CURR  MONTHS_BALANCE  CNT_INSTALMENT  CNT_INSTALMENT_FUTURE NAME_CONTRACT_STATUS  SK_DPD  SK_DPD_DEF
0     1803195      182943             -31            48.0                   45.0               Active       0           0
1     1715348      367990             -33            36.0                   35.0               Active       0           0
2     1784872      397406             -32            12.0                    9.0               Active       0           0
3     1903291      269225             -35            48.0                   42.0               Active       0           0
4     2341044      334279             -35            36.0                   35.0               Active       0           0

----------------------------------------------------------------------------------------------------


[FILE] previous_application.csv
[SHAPE PREVIEW] (5, 37)
[INFO] Key Variable Detected: 'SK_ID_CURR' (Auxiliary Table)

   SK_ID_PREV  SK_ID_CURR NAME_CONTRACT_TYPE  AMT_ANNUITY  AMT_APPLICATION  AMT_CREDIT  AMT_DOWN_PAYMENT  AMT_GOODS_PRICE WEEKDAY_APPR_PROCESS_START  HOUR_APPR_PROCESS_START FLAG_LAST_APPL_PER_CONTRACT  NFLAG_LAST_APPL_IN_DAY  RATE_DOWN_PAYMENT  RATE_INTEREST_PRIMARY  RATE_INTEREST_PRIVILEGED NAME_CASH_LOAN_PURPOSE NAME_CONTRACT_STATUS  DAYS_DECISION      NAME_PAYMENT_TYPE CODE_REJECT_REASON  NAME_TYPE_SUITE NAME_CLIENT_TYPE NAME_GOODS_CATEGORY NAME_PORTFOLIO NAME_PRODUCT_TYPE             CHANNEL_TYPE  SELLERPLACE_AREA NAME_SELLER_INDUSTRY  CNT_PAYMENT NAME_YIELD_GROUP       PRODUCT_COMBINATION  DAYS_FIRST_DRAWING  DAYS_FIRST_DUE  DAYS_LAST_DUE_1ST_VERSION  DAYS_LAST_DUE  DAYS_TERMINATION  NFLAG_INSURED_ON_APPROVAL
0     2030495      271877     Consumer loans     1730.430          17145.0     17145.0               0.0          17145.0                   SATURDAY                       15                           Y                       1                0.0               0.182832                  0.867336                    XAP             Approved            -73  Cash through the bank                XAP              NaN         Repeater              Mobile            POS               XNA             Country-wide                35         Connectivity         12.0           middle  POS mobile with interest            365243.0           -42.0                      300.0          -42.0             -37.0                        0.0
1     2802425      108129         Cash loans    25188.615         607500.0    679671.0               NaN         607500.0                   THURSDAY                       11                           Y                       1                NaN                    NaN                       NaN                    XNA             Approved           -164                    XNA                XAP    Unaccompanied         Repeater                 XNA           Cash            x-sell           Contact center                -1                  XNA         36.0       low_action          Cash X-Sell: low            365243.0          -134.0                      916.0       365243.0          365243.0                        1.0
2     2523466      122040         Cash loans    15060.735         112500.0    136444.5               NaN         112500.0                    TUESDAY                       11                           Y                       1                NaN                    NaN                       NaN                    XNA             Approved           -301  Cash through the bank                XAP  Spouse, partner         Repeater                 XNA           Cash            x-sell  Credit and cash offices                -1                  XNA         12.0             high         Cash X-Sell: high            365243.0          -271.0                       59.0       365243.0          365243.0                        1.0
3     2819243      176158         Cash loans    47041.335         450000.0    470790.0               NaN         450000.0                     MONDAY                        7                           Y                       1                NaN                    NaN                       NaN                    XNA             Approved           -512  Cash through the bank                XAP              NaN         Repeater                 XNA           Cash            x-sell  Credit and cash offices                -1                  XNA         12.0           middle       Cash X-Sell: middle            365243.0          -482.0                     -152.0         -182.0            -177.0                        1.0
4     1784265      202054         Cash loans    31924.395         337500.0    404055.0               NaN         337500.0                   THURSDAY                        9                           Y                       1                NaN                    NaN                       NaN                Repairs              Refused           -781  Cash through the bank                 HC              NaN         Repeater                 XNA           Cash           walk-in  Credit and cash offices                -1                  XNA         24.0             high         Cash Street: high                 NaN             NaN                        NaN            NaN               NaN                        NaN

----------------------------------------------------------------------------------------------------


[FILE] sample_submission.csv
[SHAPE PREVIEW] (5, 2)
[INFO] Target Variable Detected: 'TARGET' (Home Credit)

   SK_ID_CURR  TARGET
0      100001     0.5
1      100005     0.5
2      100013     0.5
3      100028     0.5
4      100038     0.5

----------------------------------------------------------------------------------------------------

## **Train, Test (Val) Split**

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
import os

RAW_DATA_PATH = '../data/raw/application_train.csv'
PROCESSED_DATA_PATH = '../data/processed/'

os.makedirs(PROCESSED_DATA_PATH, exist_ok=True)

print("Loading data...")
df = pd.read_csv(RAW_DATA_PATH)

# 2. Siddiqi Principle: Stratified Split
# In credit risk, "Defaults" (~8%) are the minority class.
# Random splitting might result in a Test set with very few or no defaults.
# By using "stratify=y", we preserve the 8% default rate in both Train and Test sets.

X = df.drop(columns=['TARGET'])
y = df['TARGET']

print("Splitting data (70% Train / 30% Test)...")

X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.30, 
    random_state=42, 
    stratify=y
)

train_df = pd.concat([X_train, y_train], axis=1)
test_df = pd.concat([X_test, y_test], axis=1)

print("Saving split datasets...")
train_df.to_csv(os.path.join(PROCESSED_DATA_PATH, 'application_train_SPLIT.csv'), index=False)
test_df.to_csv(os.path.join(PROCESSED_DATA_PATH, 'application_test_SPLIT.csv'), index=False)

print("-" * 30)
print(f"Original Data Count   : {df.shape[0]} rows")
print(f"Train Set             : {train_df.shape[0]} rows (70%)")
print(f"Test Set (Validation) : {test_df.shape[0]} rows (30%)")
print("-" * 30)
print("Target Distribution Check (Stratification Verification):")
print(f"Original Default Rate : {df['TARGET'].mean()*100:.2f}%")
print(f"Train Default Rate    : {train_df['TARGET'].mean()*100:.2f}%")
print(f"Test Default Rate     : {test_df['TARGET'].mean()*100:.2f}%")
print("-" * 30)

Loading data...
Splitting data (70% Train / 30% Test)...
Saving split datasets...
------------------------------
Original Data Count   : 307511 rows
Train Set             : 215257 rows (70%)
Test Set (Validation) : 92254 rows (30%)
------------------------------
Target Distribution Check (Stratification Verification):
Original Default Rate : 8.07%
Train Default Rate    : 8.07%
Test Default Rate     : 8.07%
------------------------------

## **Aggregation & Feature Engineering**

In [10]:
import pandas as pd

pd.set_option('display.max_colwidth', None)

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

### bureau_balance

In [12]:
from src.preprocessing import get_column_descriptions

bureau_metadata = get_column_descriptions('bureau_balance.csv')
display(bureau_metadata)

                Row                                                                                                                                                                                                                                       Description                                Special
139    SK_BUREAU_ID                                                                                                                                Recoded ID of Credit Bureau credit (unique coding for each application) - use this to join to CREDIT_BUREAU table                                  hashed
140  MONTHS_BALANCE                                                                                                                                                                Month of balance relative to application date (-1 means the freshest balance date)  time only relative to the application
141          STATUS  Status of Credit Bureau loan during the month (active, closed, DPD0-30,
 [C means closed, X means status unknown, 0 means no DPD, 1 means maximal did during month between 1-30, 2 means DPD 31-60,
 5 means DPD 120+ or sold or written off ] )                                    NaN

In [14]:
import pandas as pd
from src.aggregation import get_bureau_balance_status_dummies, get_bb_agg_logic, aggregate_bureau_balance

# Load the grandchild table
bb = pd.read_csv('../data/raw/bureau_balance.csv')

In [15]:
# Convert status categories into binary columns
bb_encoded = get_bureau_balance_status_dummies(bb)
display(bb_encoded.head())

   SK_ID_BUREAU  MONTHS_BALANCE  STATUS_0  STATUS_1  STATUS_2  STATUS_3  STATUS_4  STATUS_5  STATUS_C  STATUS_X
0       5715448               0     False     False     False     False     False     False      True     False
1       5715448              -1     False     False     False     False     False     False      True     False
2       5715448              -2     False     False     False     False     False     False      True     False
3       5715448              -3     False     False     False     False     False     False      True     False
4       5715448              -4     False     False     False     False     False     False      True     False

In [18]:
# Define the risk-based logic
logic = get_bb_agg_logic(bb_encoded)

bb_final = aggregate_bureau_balance(bb_encoded, logic)

print(f"Aggregation complete. Final shape: {bb_final.shape}")
display(bb_final.head())

Aggregation complete. Final shape: (817395, 20)

   SK_ID_BUREAU  BB_MONTHS_BALANCE_MIN  BB_MONTHS_BALANCE_MAX  BB_MONTHS_BALANCE_SIZE  BB_STATUS_0_MEAN  BB_STATUS_0_SUM  BB_STATUS_1_MEAN  BB_STATUS_1_SUM  BB_STATUS_2_MEAN  BB_STATUS_2_SUM  BB_STATUS_3_MEAN  BB_STATUS_3_SUM  BB_STATUS_4_MEAN  BB_STATUS_4_SUM  BB_STATUS_5_MEAN  BB_STATUS_5_SUM  BB_STATUS_C_MEAN  BB_STATUS_C_SUM  BB_STATUS_X_MEAN  BB_STATUS_X_SUM
0       5001709                    -96                      0                      97          0.000000                0               0.0                0               0.0                0               0.0                0               0.0                0               0.0                0          0.886598               86          0.113402               11
1       5001710                    -82                      0                      83          0.060241                5               0.0                0               0.0                0               0.0                0               0.0                0               0.0                0          0.578313               48          0.361446               30
2       5001711                     -3                      0                       4          0.750000                3               0.0                0               0.0                0               0.0                0               0.0                0               0.0                0          0.000000                0          0.250000                1
3       5001712                    -18                      0                      19          0.526316               10               0.0                0               0.0                0               0.0                0               0.0                0               0.0                0          0.473684                9          0.000000                0
4       5001713                    -21                      0                      22          0.000000                0               0.0                0               0.0                0               0.0                0               0.0                0               0.0                0          0.000000                0          1.000000               22

### bureau

In [19]:
from src.preprocessing import get_column_descriptions

bureau_metadata = get_column_descriptions('bureau.csv')
display(bureau_metadata)

                        Row                                                                                                          Description                                Special
122              SK_ID_CURR  ID of loan in our sample - one loan in our sample can have 0,1,2 or more related previous credits in credit bureau                                  hashed
123            SK_BUREAU_ID            Recoded ID of previous Credit Bureau credit related to our loan (unique coding for each loan application)                                 hashed
124           CREDIT_ACTIVE                                                                    Status of the Credit Bureau (CB) reported credits                                    NaN
125         CREDIT_CURRENCY                                                                         Recoded currency of the Credit Bureau credit                                recoded
126             DAYS_CREDIT                                   How many days before current application did client apply for Credit Bureau credit  time only relative to the application
127      CREDIT_DAY_OVERDUE                       Number of days past due on CB credit at the time of application for related loan in our sample                                    NaN
128     DAYS_CREDIT_ENDDATE                                  Remaining duration of CB credit (in days) at the time of application in Home Credit  time only relative to the application
129       DAYS_ENDDATE_FACT                        Days since CB credit ended at the time of application in Home Credit (only for closed credit)  time only relative to the application
130  AMT_CREDIT_MAX_OVERDUE                Maximal amount overdue on the Credit Bureau credit so far (at application date of loan in our sample)                                    NaN
131      CNT_CREDIT_PROLONG                                                                How many times was the Credit Bureau credit prolonged                                    NaN
132          AMT_CREDIT_SUM                                                                   Current credit amount for the Credit Bureau credit                                    NaN
133     AMT_CREDIT_SUM_DEBT                                                                                 Current debt on Credit Bureau credit                                    NaN
134    AMT_CREDIT_SUM_LIMIT                                                        Current credit limit of credit card reported in Credit Bureau                                    NaN
135  AMT_CREDIT_SUM_OVERDUE                                                                       Current amount overdue on Credit Bureau credit                                    NaN
136             CREDIT_TYPE                                                                         Type of Credit Bureau credit (Car, cash,...)                                    NaN
137      DAYS_CREDIT_UPDATE                       How many days before loan application did last information about the Credit Bureau credit come  time only relative to the application
138             AMT_ANNUITY                                                                                  Annuity of the Credit Bureau credit                                    NaN

In [20]:
bureau = pd.read_csv('../data/raw/bureau.csv')

bureau_combined = bureau.merge(bb_final, on='SK_ID_BUREAU', how='left')

print(f"Combined table shape: {bureau_combined.shape}")

Combined table shape: (1716428, 36)

In [21]:
display(bureau_combined.head().T)

                                      0            1                2            3                4
SK_ID_CURR                       215354       215354           215354       215354           215354
SK_ID_BUREAU                    5714462      5714463          5714464      5714465          5714466
CREDIT_ACTIVE                    Closed       Active           Active       Active           Active
CREDIT_CURRENCY              currency 1   currency 1       currency 1   currency 1       currency 1
DAYS_CREDIT                        -497         -208             -203         -203             -629
CREDIT_DAY_OVERDUE                    0            0                0            0                0
DAYS_CREDIT_ENDDATE              -153.0       1075.0            528.0          NaN           1197.0
DAYS_ENDDATE_FACT                -153.0          NaN              NaN          NaN              NaN
AMT_CREDIT_MAX_OVERDUE              NaN          NaN              NaN          NaN          77674.5
CNT_CREDIT_PROLONG                    0            0                0            0                0
AMT_CREDIT_SUM                  91323.0     225000.0         464323.5      90000.0        2700000.0
AMT_CREDIT_SUM_DEBT                 0.0     171342.0              NaN          NaN              NaN
AMT_CREDIT_SUM_LIMIT                NaN          NaN              NaN          NaN              NaN
AMT_CREDIT_SUM_OVERDUE              0.0          0.0              0.0          0.0              0.0
CREDIT_TYPE             Consumer credit  Credit card  Consumer credit  Credit card  Consumer credit
DAYS_CREDIT_UPDATE                 -131          -20              -16          -16              -21
AMT_ANNUITY                         NaN          NaN              NaN          NaN              NaN
BB_MONTHS_BALANCE_MIN               NaN          NaN              NaN          NaN              NaN
BB_MONTHS_BALANCE_MAX               NaN          NaN              NaN          NaN              NaN
BB_MONTHS_BALANCE_SIZE              NaN          NaN              NaN          NaN              NaN
BB_STATUS_0_MEAN                    NaN          NaN              NaN          NaN              NaN
BB_STATUS_0_SUM                     NaN          NaN              NaN          NaN              NaN
BB_STATUS_1_MEAN                    NaN          NaN              NaN          NaN              NaN
BB_STATUS_1_SUM                     NaN          NaN              NaN          NaN              NaN
BB_STATUS_2_MEAN                    NaN          NaN              NaN          NaN              NaN
BB_STATUS_2_SUM                     NaN          NaN              NaN          NaN              NaN
BB_STATUS_3_MEAN                    NaN          NaN              NaN          NaN              NaN
BB_STATUS_3_SUM                     NaN          NaN              NaN          NaN              NaN
BB_STATUS_4_MEAN                    NaN          NaN              NaN          NaN              NaN
BB_STATUS_4_SUM                     NaN          NaN              NaN          NaN              NaN
BB_STATUS_5_MEAN                    NaN          NaN              NaN          NaN              NaN
BB_STATUS_5_SUM                     NaN          NaN              NaN          NaN              NaN
BB_STATUS_C_MEAN                    NaN          NaN              NaN          NaN              NaN
BB_STATUS_C_SUM                     NaN          NaN              NaN          NaN              NaN
BB_STATUS_X_MEAN                    NaN          NaN              NaN          NaN              NaN
BB_STATUS_X_SUM                     NaN          NaN              NaN          NaN              NaN

In [22]:
non_nan_count = bureau_combined['BB_MONTHS_BALANCE_SIZE'].notnull().sum()
total_count = len(bureau_combined)

print(f"Toplam Kredi Sayısı: {total_count}")
print(f"BB Verisi Olan Kredi Sayısı: {non_nan_count}")
print(f"Doluluk Oranı: %{round(non_nan_count / total_count * 100, 2)}")

Toplam Kredi Sayısı: 1716428
BB Verisi Olan Kredi Sayısı: 774354
Doluluk Oranı: %45.11

In [23]:
currency_counts = bureau['CREDIT_CURRENCY'].value_counts(normalize=True)
print(currency_counts)

CREDIT_CURRENCY
currency 1    0.999180
currency 2    0.000713
currency 3    0.000101
currency 4    0.000006
Name: proportion, dtype: float64

In [24]:
closed_bureau = bureau[bureau['CREDIT_ACTIVE'] == 'Closed']

correlation = closed_bureau[['DAYS_ENDDATE_FACT', 'DAYS_CREDIT_ENDDATE']].corr()
print(f"Kapalı Kredilerde Benzerlik Korelasyonu:\n{correlation}")

diff = (closed_bureau['DAYS_ENDDATE_FACT'] - closed_bureau['DAYS_CREDIT_ENDDATE']).abs().mean()
print(f"Ortalama Gün Farkı: {diff}")

Kapalı Kredilerde Benzerlik Korelasyonu:
                     DAYS_ENDDATE_FACT  DAYS_CREDIT_ENDDATE
DAYS_ENDDATE_FACT             1.000000             0.248398
DAYS_CREDIT_ENDDATE           0.248398             1.000000
Ortalama Gün Farkı: 526.8716359133979

In [29]:
from src.aggregation import  get_bureau_dummies, get_bureau_aggregation_logic, aggregate_bureau_data

ImportError: cannot import name 'get_bureau_dummies' from 'src.aggregation' (c:\Users\Eren\Desktop\Credit_Risk_Analyse\src\aggregation.py)

In [ ]:
bureau_combined_encoded = get_bureau_dummies(bureau_combined)

bureau_logic = get_bureau_aggregation_logic(bureau_combined_encoded)

bureau_final_summary = aggregate_bureau_data(bureau_combined_encoded, bureau_logic)

In [ ]:
print(f"Aggregation complete. Final shape: {bureau_final_summary.shape}")
display(bureau_final_summary.head())